
version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): update actions"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): update npm dependencies"
    groups:
      eslint:
        applies-to: version-updates
        patterns:
        - "eslint*"
        - "@typescript-eslint*"
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): update go dependencies"
