services:
  minichat:
    image: ghcr.io/nineteenseventy/minichat:latest
    environment:
      - PGHOST=postgres
      - PGDATABASE=minichat
      - PGUSERNAME=postgres
      - PGPASSWORD=postgres
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESSKEY=minioadmin
      - MINIO_SECRETKEY=minioadmin
      - CACHE_TYPE=redis
      - REDIS_HOST=redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minichat
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest

  nginx:
    image: nginx:alpine
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'

volumes:
  minio-data:
  postgres-data:
